# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'Cubstart-Sentiment-Analysis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cubstart-Sentiment-Analysis

  target 'Cubstart-Sentiment-AnalysisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cubstart-Sentiment-AnalysisUITests' do
    # Pods for testing
  end

end
